export const jobProfileFormInfo: jobProfileFeildInfoType = {
   name: "আপনার পুরো নাম \n\"ইংরেজিতে\"",
   name_bn: "আপনার পুরো নাম \n\"বাংলায়\"",
   father: "বাবার নাম লিখুন \n\"ইংরেজিতে\"",
   father_bn: "বাবার নাম লিখুন \n\"বাংলায়\"",
   mother: "মায়ের নাম লিখুন \n\"ইংরেজিতে\"",
   mother_bn: "মায়ের নাম লিখুন \n\"বাংলায়\"",
   dob: "জন্ম তারিখ ইংরেজিতে \"বছর-মাস-তারিখ\"যেমনঃ\n 1991-10-20",
   religion: "Islam\n  Hinduism\n  Buddhism\n  Christianity",
   gender: "Male\n Female\n Other",
   nid_no: "জাতীয় পরিচয়পত্র নম্বর \n\"ইংরেজিতে\"",
   breg_no: "জন্ম নিবন্ধন নম্বর \n\"ইংরেজিতে\"",
   passport: "Yes\n No",
   passport_no: "পাসপোর্ট নম্বর \n\"ইংরেজিতে\"",
   marital_status: "Single\n Married \n Other",
   mobile: "মোবাইল নম্বর \"ইংরেজিতে\"",
   confirm_mobile: "মোবাইল নম্বর নিশ্চিত করুন",
   email: "ইমেইল এড্রেস",
   quota: "Child of Freedom Fighter\n Grand Child of Freedom Fighter\n Physically Handicapped\n Orphan\n Ethnic Minority\nAnsar-VDP\n Non Quota",
   dep_status: "Govt. Employee\nGovt. Employee\nAutonomous\nDepartmental Candidate\nNone",
   present_careof: "বর্তমান অভিভাবকের নাম \n\"ইংরেজিতে\"",
   present_village: "বর্তমান গ্রাম/টাউন/রাস্তা/বাড়ি/ফ্লাট",
   present_district: "বর্তমান জেলা",
   present_upazila: "বর্তমান উপজেলা",
   present_post: "বর্তমান ডাকঘর",
   present_postcode: "বর্তমান পোস্টকোড",
   permanent_careof: "স্থায়ী অভিভাবকের নাম \n\"ইংরেজিতে\"",
   permanent_village: "স্থায়ী গ্রাম/টাউন/রাস্তা/বাড়ি/ফ্লাট \n\"ইংরেজিতে\"",
   permanent_district: "স্থায়ী জেলা \n\"ইংরেজিতে\"",
   permanent_upazila: "স্থায়ী উপজেলা \n\"ইংরেজিতে\"",
   permanent_post: "স্থায়ী ডাকঘর \n\"ইংরেজিতে\"",
   permanent_postcode: "স্থায়ী পোস্টকোড \n\"ইংরেজিতে\"",
   ssc_exam: "S.S.C\nDakhil\nS.S.C Vocational\nO Level/Cambridge\nS.S.C Equivalent\nDakhil Vocational",
   ssc_roll: "রোল নম্বর \n\"ইংরেজিতে\"",
   ssc_group: "Business Studies\nGeneral\nHumanities\nScience\nOther",
   ssc_board: "Dhaka\nCumilla\nRajshahi\nJashore \nChattogram\nBarishal\nSylhet\nDinajpur\nMymensingh\nMadrasha\nOpen University\nThe State Medical Faculty of Bangladesh\nPharmacy Council of Bangladesh\nCambridge International - IGCE\nEdexcel International\nBangladesh Technical Education Board (BTEB)\nOther",
   ssc_result_type: "1st Division\n2nd Division\n3rd Division\nGPA(out of 4)\nGPA(out of 5)",
   ssc_result: "গ্রেড পয়েন্ট\n\"ইংরেজিতে\"",
   ssc_year: "পাশের সাল\n\"ইংরেজিতে\"",
   hsc_exam: "H.S.C\nAlim\nBusiness Management\nDiploma-in-Engineering\nA Level/Sr. Cambridge\nH.S.C Equivalent\nDiploma in Medical Technology\nH.S.C Vocational",
   hsc_roll: "রোল নম্বর \n\"ইংরেজিতে\"",
   hsc_group: "Business Studies\nGeneral\nHumanities\nScience\nOther",
   hsc_board: "Dhaka\nCumilla\nRajshahi\nJashore \nChattogram\nBarishal\nSylhet\nDinajpur\nMymensingh\nMadrasha\nOpen University\nThe State Medical Faculty of Bangladesh\nPharmacy Council of Bangladesh\nCambridge International - IGCE\nEdexcel International\nBangladesh Technical Education Board (BTEB)\nOther",
   hsc_result_type: "1st Division\n2nd Division\n3rd Division\nGPA(out of 4)\nGPA(out of 5)",
   hsc_result: "গ্রেড পয়েন্ট\n\"ইংরেজিতে\"",
   hsc_year: "পাশের সাল\n\"ইংরেজিতে\"",
   gra_exam: "B.Sc Engineering\nB.Sc in Agricultural Science\nHonors",
   gra_institute: "Ad-din Womens Medical College, Dhaka\nAhsania Mission University of Science and Technology\nAhsanullah University of Science and Technology\nAmerica Bangladesh University\nAmerican International University Bangladesh \nNational University",
   gra_year: "পাশের সাল\n\"ইংরেজিতে\"",
   gra_subject: "Agriculture\nBiochemistry\nComputer Science\nComputer Science & Engineering\nEnvironmental science\nForestry",
   gra_result_type: "1st Class\n2nd Class\n3rd Class\nGPA(out of 4)\nGPA(out of 5)\nPassed",
   gra_result: "গ্রেড পয়েন্ট\n\"ইংরেজিতে\"",
   gra_duration: "03 Years\n04 Years\n05 Years",
   if_applicable_mas: "string",
   mas_exam: "M.A\nM.S.S\nM.Sc\nM.Com\nM.B.A\nL.L.M\nM.Phil\nKamil\nMasters Equivalent",
   mas_institute: "Ad-din Womens Medical College, Dhaka\nAhsania Mission University of Science and Technology\nAhsanullah University of Science and Technology\nAmerica Bangladesh University\nAmerican International University Bangladesh\n National University",
   mas_year: "পাশের সাল\n\"ইংরেজিতে\"",
   mas_subject: "Agriculture\nBiochemistry\nComputer Science\nComputer Science & Engineering\nEnvironmental science\nForestry",
   mas_result_type: "1st Class\n2nd Class\n3rd Class\nGPA(out of 4)\nGPA(out of 5)\nPassed",
   mas_result: "গ্রেড পয়েন্ট\n\"ইংরেজিতে\"",
   mas_duration: "01 Year\n1.5 Years\n02 Years\n2.5 Years\n03 Years\n3+ Years",
}